Release 0.3.0
### Features

* Add git to build-amazonlinux2 image
* Add google-java-format pre-commit hook
* Add OpenJDK 11
* Move python3 to /opt/bin/python3

### Bug Fixes

* Ensure builder::set_workspace does not overwrite WORKSPACE

Change-Id: I196b8577c2812e400ab5cf71edeb0815bb818b66
GitOrigin-RevId: fcf3b2f2b77bbaa1de132885f669ee8a4871f993

diff --git a/tools/get-builder-image-tagged b/tools/get-builder-image-tagged
--- a/tools/get-builder-image-tagged
+++ b/tools/get-builder-image-tagged
@@ -23,6 +23,18 @@ set -o errexit
 VERBOSE=0
 BUILD_IMAGE_IF_NEEDED=1
 
+trap _cleanup EXIT
+function _cleanup() {
+  declare -r -i STATUS=$?
+  if [[ -n ${TEMPTAR} ]]; then
+    rm -f "${TEMPTAR}"
+  fi
+  if [[ ${STATUS} -ne 0 ]]; then
+    printf "Error: get-builder-image-tagged status code: %d\n" "${STATUS}" &>/dev/stderr
+  fi
+  exit ${STATUS}
+}
+
 declare -r -A IMAGE_NAMES=(
   [build-debian]="privacysandbox/builders/build-debian"
   [build-amazonlinux2]="privacysandbox/builders/build-amazonlinux2"
@@ -31,9 +43,9 @@ declare -r -A IMAGE_NAMES=(
   [utils]="privacysandbox/builders/utils"
 )
 
-usage() {
+function usage() {
   declare -r -i exitval=${1-1}
-  cat &>/dev/stderr << USAGE
+  cat &>/dev/stderr <<USAGE
 usage:
   $0 <options>
     --no-build           Do not build image if it doesn't exist
@@ -48,7 +60,7 @@ USAGE
     printf "                             *  %s%s\n" "${elem}" "${EXTRA}" &>/dev/stderr
   done
 
-  cat &>/dev/stderr << USAGE
+  cat &>/dev/stderr <<USAGE
     --verbose            Enable verbose output
 USAGE
   # shellcheck disable=SC2086
@@ -103,14 +115,6 @@ if ! [[ -s ${IMAGE_PATH_FULL}/Dockerfile ]]; then
 fi
 TEMPTAR="$(mktemp --dry-run --suffix=.tar.gz)"
 readonly TEMPTAR
-
-trap _cleanup EXIT
-
-function _cleanup() {
-  declare -r -i STATUS=$?
-  rm -f "${TEMPTAR}"
-  exit ${STATUS}
-}
 
 # Try to create a deterministic tar file for the specified file path
 # Any etc files in the $WORKSPACE (root) directory override the etc
